import { ProgramType } from "./types";

export const AllProgramsData: ProgramType[] = [
  {
    universityName: "University of Delhi",
    universityType: "State",
    country: "India",
    gradeType: "Bachelor Degree",
    educationType: "Full Time",
    campusType: "On Campus",
    educationLanguage: "English",
    fee: 5000,
    discountFee: 4500,
    featured: true,
    course: "Computer Science",
  },
  {
    universityName: "Kuala Lumpur University",
    universityType: "State",
    country: "Malaysia",
    gradeType: "Master with Thesis",
    educationType: "Online",
    campusType: "Off Campus",
    educationLanguage: "English",
    fee: 8000,
    discountFee: 7000,
    featured: false,
    course: "Business Administration",
  },
  {
    universityName: "Istanbul Technical University",
    universityType: "State",
    country: "Turkey",
    gradeType: "PhD",
    educationType: "Evening Period",
    campusType: "On Campus",
    educationLanguage: "Turkish",
    fee: 7000,
    discountFee: 6500,
    featured: true,
    course: "Engineering",
  },
  {
    universityName: "University of Sarajevo",
    universityType: "State",
    country: "Bosnia",
    gradeType: "Associate Degree",
    educationType: "Full Time",
    campusType: "On Campus",
    educationLanguage: "German",
    fee: 3000,
    discountFee: 2700,
    featured: false,
    course: "Economics",
  },
  {
    universityName: "Istanbul University",
    universityType: "State",
    country: "Turkey",
    gradeType: "Master without Thesis",
    educationType: "Online",
    campusType: "Off Campus",
    educationLanguage: "English",
    fee: 5500,
    discountFee: 5000,
    featured: true,
    course: "History",
  },
  {
    universityName: "University of Kuala Lumpur",
    universityType: "Private",
    country: "Malaysia",
    gradeType: "Bachelor Degree",
    educationType: "Full Time",
    campusType: "On Campus",
    educationLanguage: "English",
    fee: 6000,
    discountFee: 5500,
    featured: false,
    course: "Business Administration",
  },
  {
    universityName: "Ankara University",
    universityType: "State",
    country: "Turkey",
    gradeType: "PhD",
    educationType: "Full Time",
    campusType: "On Campus",
    educationLanguage: "Turkish",
    fee: 7500,
    discountFee: 7000,
    featured: true,
    course: "Medicine",
  },
  {
    universityName: "University of Istanbul",
    universityType: "State",
    country: "Turkey",
    gradeType: "Master with Thesis",
    educationType: "Online",
    campusType: "Off Campus",
    educationLanguage: "English",
    fee: 8000,
    discountFee: 7500,
    featured: false,
    course: "Computer Science",
  },
  {
    universityName: "University of Sarajevo",
    universityType: "State",
    country: "Bosnia",
    gradeType: "Associate Degree",
    educationType: "Evening Period",
    campusType: "On Campus",
    educationLanguage: "Turkish",
    fee: 3500,
    discountFee: 3200,
    featured: true,
    course: "Economics",
  },
  {
    universityName: "Malaysia University",
    universityType: "Private",
    country: "Malaysia",
    gradeType: "Bachelor Degree",
    educationType: "Full Time",
    campusType: "On Campus",
    educationLanguage: "English",
    fee: 6500,
    discountFee: 6000,
    featured: false,
    course: "Business Administration",
  },
  {
    universityName: "Bosnia and Herzegovina University",
    universityType: "State",
    country: "Bosnia",
    gradeType: "PhD",
    educationType: "Full Time",
    campusType: "On Campus",
    educationLanguage: "Chinese",
    fee: 7200,
    discountFee: 6800,
    featured: true,
    course: "Medicine",
  },
  {
    universityName: "Istanbul Technical University",
    universityType: "State",
    country: "Turkey",
    gradeType: "Master without Thesis",
    educationType: "Online",
    campusType: "Off Campus",
    educationLanguage: "English",
    fee: 5800,
    discountFee: 5400,
    featured: false,
    course: "Computer Science",
  },
  {
    universityName: "New Delhi University",
    universityType: "State",
    country: "India",
    gradeType: "Bachelor Degree",
    educationType: "Evening Period",
    campusType: "On Campus",
    educationLanguage: "English",
    fee: 5500,
    discountFee: 5000,
    featured: true,
    course: "Business Administration",
  },
  {
    universityName: "Kuala Lumpur University",
    universityType: "State",
    country: "Malaysia",
    gradeType: "PhD",
    educationType: "Online",
    campusType: "Off Campus",
    educationLanguage: "English",
    fee: 7800,
    discountFee: 7500,
    featured: false,
    course: "Engineering",
  },
  {
    universityName: "Ankara University",
    universityType: "State",
    country: "Turkey",
    gradeType: "Associate Degree",
    educationType: "Full Time",
    campusType: "On Campus",
    educationLanguage: "Turkish",
    fee: 4000,
    discountFee: 3700,
    featured: true,
    course: "Economics",
  },
  {
    universityName: "University of Istanbul",
    universityType: "State",
    country: "Turkey",
    gradeType: "Master with Thesis",
    educationType: "Online",
    campusType: "Off Campus",
    educationLanguage: "English",
    fee: 8200,
    discountFee: 7800,
    featured: true,
    course: "Computer Science",
  },
  {
    universityName: "University of Sarajevo",
    universityType: "State",
    country: "Bosnia",
    gradeType: "Bachelor Degree",
    educationType: "Evening Period",
    campusType: "On Campus",
    educationLanguage: "Arabic",
    fee: 4500,
    discountFee: 4200,
    featured: false,
    course: "Economics",
  },
];
